spring:
  application:
    name: Task-Manager
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: mydatabase
  cassandra:
    keyspace-name: task_manager_keyspace
    port: 9042
    contact-points: 127.0.0.1
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
  redis:
    host: localhost
    port: 6379
    password: password
  cache:
    type: redis

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG